name: 01 - Hello

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "¡Hola, mundo! esto es un prueba locaaa"

      - name: Ver fecha del codigo
        run: date

      - name: Ver archivos disponibles
        run: ls -la

  repo-files:
    runs-on: ubuntu-slim
    steps:
      - name: Descargar todo el codigo del repo.
        uses: actions/checkout@v7

      - name: Ver archivos del repo
        run: ls -la
